# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fn.proto',
  package='fn',
  syntax='proto3',
  serialized_pb=_b('\n\x08\x66n.proto\x12\x02\x66n\"\x1f\n\x07Request\x12\x14\n\x0cimg_filepath\x18\x01 \x01(\t\"\x1b\n\x05Reply\x12\x12\n\nannotation\x18\x01 \x01(\t21\n\x02NN\x12+\n\x0fGetSegmentation\x12\x0b.fn.Request\x1a\t.fn.Reply\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='fn.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_filepath', full_name='fn.Request.img_filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=47,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='fn.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='annotation', full_name='fn.Reply.annotation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'fn_pb2'
  # @@protoc_insertion_point(class_scope:fn.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'fn_pb2'
  # @@protoc_insertion_point(class_scope:fn.Reply)
  ))
_sym_db.RegisterMessage(Reply)



_NN = _descriptor.ServiceDescriptor(
  name='NN',
  full_name='fn.NN',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=78,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSegmentation',
    full_name='fn.NN.GetSegmentation',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NN)

DESCRIPTOR.services_by_name['NN'] = _NN

# @@protoc_insertion_point(module_scope)
