# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fn_pb2 as fn__pb2


class NNStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSegmentation = channel.unary_unary(
        '/fn.NN/GetSegmentation',
        request_serializer=fn__pb2.Request.SerializeToString,
        response_deserializer=fn__pb2.Reply.FromString,
        )


class NNServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSegmentation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NNServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSegmentation': grpc.unary_unary_rpc_method_handler(
          servicer.GetSegmentation,
          request_deserializer=fn__pb2.Request.FromString,
          response_serializer=fn__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fn.NN', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
